applications/urls.py
from django.urls import path
from applications.views import ApplicationCreateView, ApplicationDeleteView, ApplicationUpdateView, \
    ApplicationStatus2DeleteView, ApplicationStatus1DeleteView, ProductByeCreateView, my_product_read, \
    applications_main, user_read_product, user_bye_product, user_bye_one_product, bye_product_read

app_name = 'applications'
urlpatterns = [


    # path('applications/', ApplicationListView.as_view(), name='applications_read'),
    path('applications/', applications_main, name='applications_read'),
    path('applications/create/', ApplicationCreateView.as_view(), name='applications_create'),
    path('applications-delete/<int:pk>/', ApplicationDeleteView.as_view(), name='applications_delete'),
    path('applications-update/<int:pk>/', ApplicationUpdateView.as_view(), name='applications_update'),
    path('applications-update-status1/<int:pk>/', ApplicationStatus1DeleteView.as_view(), name='applications_update_status1'),
    path('applications-update-status2/<int:pk>/', ApplicationStatus2DeleteView.as_view(), name='applications_update_status2'),
    path('product_bye/<int:pk>/', ProductByeCreateView.as_view(), name='product_bye'),
    path('product_read/', my_product_read, name='product_read'),
    path('user_read_product/', user_read_product, name='user_read_product'),
    path('user_bye_product/<str:user_name>/<str:city>/', user_bye_product, name='user_bye_product'),
    path('user_bye_one_product/<int:id>/', user_bye_one_product, name='user_bye_one_product'),
    # path('product_bye.html/<int:pk>/', product_bye, name='product_bye'),
    path('bye_product_read/', bye_product_read, name='bye_product_read'),

]

baskets/urls.py
from django.urls import path

from baskets.views import basket_remove,basket_edit

app_name = 'baskets'
urlpatterns = [

    # path('add/<int:id>/', basket_add,name='basket_add'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id_basket>/<int:quantity>/', basket_edit, name='basket_edit'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('user_works/', include('user_works.urls', namespace='user_works')),
    # path('admins/', include('admins.urls', namespace='admins')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baskets/models.py
from django.db import models


# Create your models here.
from authapp.models import User
from mainapp.models import Product



class Basket(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    create_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для  {self.user.username} | Продукт{self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    # @property
    # def get_baskets(self):
    #     baskets = Basket.objects.filter(user=self.user)
    #     return baskets

    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.sum() for basket in baskets)

    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.quantity for basket in baskets)

baskets/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

# Create your views here.
from django.template.loader import render_to_string

from baskets.models import Basket
from mainapp.models import Product

# @login_required
# def basket_add(request,id):
#     user_select = request.user
#     product = Product.objects.get(id=id)
#     baskets = Basket.objects.filter(user=user_select,product=product)
#     if baskets:
#         basket = baskets.first()
#         basket.quantity +=1
#         basket.save()
#     else:
#         Basket.objects.create(user=user_select,product=product,quantity=1)
#     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# @login_required
# def basket_add(request,id):
#     if request.is_ajax():
#         user_select = request.user
#         product = Product.objects.get(id=id)
#         baskets = Basket.objects.filter(user=user_select,product=product)
#         if baskets:
#             basket = baskets.first()
#             basket.quantity +=1
#             basket.save()
#         else:
#             Basket.objects.create(user=user_select,product=product,quantity=1)
#
#         products = Product.objects.all()
#         context = {'products': products}
#         result = render_to_string('mainapp/includes/card.html', context)
#         return JsonResponse({'result': result})



@login_required
def basket_remove(request,basket_id):
    Basket.objects.get(id=basket_id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_edit(request,id_basket,quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id_basket)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()

        baskets = Basket.objects.filter(user=request.user)
        context = {'baskets':baskets}
        result = render_to_string('baskets/basket.html',context)
        test = JsonResponse({'result':result})
        return test

baskets/templates/baskets/basket.html
<div class="basket_list">
    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="1">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }}</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ baskets.0.total_sum }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% else %}
        <h4 class="mt-3 mb-3 text-center">Корзина пуста</h4>
    {% endif %}
</div>

baskets/templates/baskets/basket1.html
{% extends 'applications/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукта
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя дилера</th>
                                    <th>Тема заявки</th>
                                    <th>Грород дилера</th>
                                    <th>Описание</th>
                                    <th>Статус</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>

                                </tr>
                                <tbody>
                                {% for application in applications %}
                                    <tr>
                                        <td>{{ application.user_name }}</td>
                                        <td>{{ application.name }}</td>
                                        <td>{{ application.city }}</td>
                                        <td>{{ application.description }}</td>
                                        <td>
                                            {% if request.user.user_role != 'Сотрудник' and application.is_active == 'Одобрено' %}
                                                <a href="{% url 'applications:bye_product_read' %}">{{ application.is_active }}</a>
<!--                                                <a href="{% url 'applications:product_bye' application.id %}">{{ application.is_active }}</a>-->
                                            {% else%}
                                                {{ application.is_active }}
                                            {%endif%}
                                        </td>
                                        <td>
                                            {% if request.user.user_role == 'Сотрудник'%}

                                            <form action="{% url 'applications:applications_update_status1' application.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Отказать">
                                            </form>
                                            {%else%}
                                            <form action="{% url 'applications:applications_delete' application.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                                            </form>
                                            {%endif%}
                                        </td>
                                        <td>
                                            {% if request.user.user_role == 'Сотрудник'%}
                                            <form action="{% url 'applications:applications_update_status2' application.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-success btn-block" type="submit" value="Одобрить">
                                            </form>
                                            {%else%}
                                            <a href="{% url 'applications:applications_update' application.id %}">
                                                <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                            </a>
                                            {%endif%}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% if request.user.user_role != 'Сотрудник'%}
                    <div class="card-footer">
                        <a href="{% url 'applications:applications_create' %}">
                            <button class="btn btn-success">Сформировать заявку</button>
                        </a>
                    </div>
                    {%endif%}
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">

            </div>
        </footer>
    </div>

{% endblock %}