applications/urls.py
from django.urls import path
from applications.views import ApplicationCreateView, ApplicationDeleteView, ApplicationUpdateView, \
    ApplicationStatus2DeleteView, ApplicationStatus1DeleteView, ProductByeCreateView, my_product_read, \
    applications_main, user_read_product, user_bye_product, user_bye_one_product, bye_product_read

app_name = 'applications'
urlpatterns = [


    # path('applications/', ApplicationListView.as_view(), name='applications_read'),
    path('applications/', applications_main, name='applications_read'),
    path('applications/create/', ApplicationCreateView.as_view(), name='applications_create'),
    path('applications-delete/<int:pk>/', ApplicationDeleteView.as_view(), name='applications_delete'),
    path('applications-update/<int:pk>/', ApplicationUpdateView.as_view(), name='applications_update'),
    path('applications-update-status1/<int:pk>/', ApplicationStatus1DeleteView.as_view(), name='applications_update_status1'),
    path('applications-update-status2/<int:pk>/', ApplicationStatus2DeleteView.as_view(), name='applications_update_status2'),
    path('product_bye/<int:pk>/', ProductByeCreateView.as_view(), name='product_bye'),
    path('product_read/', my_product_read, name='product_read'),
    path('user_read_product/', user_read_product, name='user_read_product'),
    path('user_bye_product/<str:user_name>/<str:city>/', user_bye_product, name='user_bye_product'),
    path('user_bye_one_product/<int:id>/', user_bye_one_product, name='user_bye_one_product'),
    # path('product_bye.html/<int:pk>/', product_bye, name='product_bye'),
    path('bye_product_read/', bye_product_read, name='bye_product_read'),

]

authapp/urls.py
from django.urls import path
# from authapp.views import
from authapp.views import login,register,logout,profile

app_name = 'authapp'
urlpatterns = [

    path('login/', login,name='login'),
    path('register/', register,name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('user_works/', include('user_works.urls', namespace='user_works')),
    # path('admins/', include('admins.urls', namespace='admins')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/models.py
from django.db import models

from authapp.models import User
from mainapp.models import Product, Product_for_diller

colors_telephone = [
    ('black', 'black'),
    ('yellow', 'yellow'),
    ('white', 'white'),
]


class ApplicationModel(models.Model):
    name = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    is_active = models.CharField(default='в обработке', max_length=128)

    def __str__(self):
        return f'{self.name}'


class MyProductsModel(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    name_application = models.ForeignKey(ApplicationModel, on_delete=models.CASCADE)
    model = models.ForeignKey(Product_for_diller, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    price = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.model}'

applications/forms.py
from django import forms

from applications.models import ApplicationModel, MyProductsModel
from mainapp.models import Product


class ApplicationForm(forms.ModelForm):
    class Meta(object):
        model = ApplicationModel
        fields = ('user_name', 'name', 'city', 'description', 'is_active')

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class ApplicationUpdateForm(forms.ModelForm):
    class Meta(object):
        model = ApplicationModel
        fields = ('name', 'city', 'description')

    def __init__(self, *args, **kwargs):
        super(ApplicationUpdateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

        # self.object.quantity += instance.quantity
        # self.object.save()

        # form.instance.testing += self.object.testing
        # my_object = MyProductsModel.objects.get_or_create(pk=self.kwargs.get('pk'), model=instance.model)
        # my_object = MyProductsModel.objects.filter(model=instance.model)
        # if my_object.first() is not None:
class ProductBye(forms.ModelForm):
    class Meta(object):
        model = MyProductsModel
        fields = ( 'model', 'quantity')

    def __init__(self, *args, **kwargs):
        super(ProductBye, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

applications/views.py
from email._header_value_parser import Section

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, DetailView, TemplateView
# Create your views here.
from pyexpat.errors import messages
from django import forms
from applications.forms import ApplicationForm, ApplicationUpdateForm, ProductBye
from applications.models import ApplicationModel, MyProductsModel
from authapp.models import User
from cart.form import CartAddProductForm
from mainapp.admin import Product
from mainapp.mixin import BaseClassContextMixin, CustomDispatchMixin

# class ApplicationListView(ListView, BaseClassContextMixin):
#     model = ApplicationModel
#     template_name = 'applications/applications-read.html'
#     title = 'Сформированные заявки'
from mainapp.models import Product_for_diller


def applications_main(request):
    if request.user.user_role == 'Сотрудник':
        applications = ApplicationModel.objects.all()
    else:
        applications = ApplicationModel.objects.filter(user_name=request.user)
    context = {'applications': applications}
    return render(request, 'applications/applications-read.html', context)


class ApplicationStatus1DeleteView(DeleteView, BaseClassContextMixin):
    model = ApplicationModel
    template_name = 'applications/applications-update-delete.html'
    success_url = reverse_lazy('applications:applications_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = 'Отклонено'
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ApplicationStatus2DeleteView(DeleteView, BaseClassContextMixin):
    model = ApplicationModel
    template_name = 'applications/applications-update-delete.html'
    success_url = reverse_lazy('applications:applications_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = 'Одобрено'
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ApplicationCreateView(CreateView, BaseClassContextMixin):
    model = ApplicationModel
    template_name = 'applications/applications-create.html'
    form_class = ApplicationUpdateForm
    # permission_required = 'news.add_post'
    success_url = reverse_lazy('applications:applications_read')
    title = 'Формирование заявки'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user_name = self.request.user

        super().form_valid(form)
        instance.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductByeCreateView(CreateView):
    model = MyProductsModel
    template_name = 'applications/product_bye.html'
    form_class = ProductBye
    success_url = reverse_lazy('applications:applications_read')

    def get_context_data(self, **kwargs):
        application = ApplicationModel.objects.filter(pk=self.kwargs.get('pk'))
        context = super().get_context_data(**kwargs)
        context["applications"] = application
        return context

    def form_valid(self, form, **kwargs):
        instance = form.save(commit=False)
        instance.name_application = ApplicationModel.objects.get(pk=self.kwargs.get('pk'))
        instance.user_name = self.request.user
        objs = MyProductsModel.objects.filter(name_application=instance.name_application, model=instance.model)
        obj_dealer = Product_for_diller.objects.get(model=instance.model)
        obj_dealer.quantity -= instance.quantity
        if obj_dealer.quantity > 0:
            obj_dealer.save()
        else:
            obj_dealer.delete()
        if objs:
            obj = objs.first()
            print(obj.name_application.user_name)
            obj.quantity += instance.quantity
            obj.save()
            return HttpResponseRedirect(reverse('applications:applications_read'))
        super().form_valid(form)
        instance.save()
        return HttpResponseRedirect(self.get_success_url())


# class MyProductsListView(ListView, BaseClassContextMixin):
#     model = MyProductsModel
#     queryset = MyProductsModel.objects.filter(name_application='Продажа ноутбуков')
#     template_name = 'applications/read_my_product.html'
#     title = 'Мой склад'


def my_product_read(request):
    # name_applications = ApplicationModel.objects.filter(user_name=request.user)
    # print(name_applications)
    products = MyProductsModel.objects.filter(user_name=request.user)
    context = {'object_list': products}
    return render(request, 'applications/read_my_product.html', context)


def bye_product_read(request):
    applications = ApplicationModel.objects.filter(user_name=request.user, is_active='Одобрено')
    products = []
    for application in applications:
        products.extend(list(Product_for_diller.objects.filter(name=application.name)))
    cart_product_form = CartAddProductForm()
    context = {'products': products, 'cart_product_form': cart_product_form}
    return render(request, 'applications/bye_product_read.html', context)


def user_read_product(request):
    products = ApplicationModel.objects.filter(is_active='Одобрено', user_name__user_role='Дилер')
    context = {'products': products}
    return render(request, 'applications/user_read_city.html', context)


def user_bye_product(request, user_name, city):
    products = MyProductsModel.objects.filter(user_name__username=user_name)
    # , name_application__city=city добавить в фильтр
    cart_product_form = CartAddProductForm()
    context = {'products': products, 'cart_product_form': cart_product_form}
    return render(request, 'applications/user_bye_products.html', context)


def user_bye_one_product(request, id):
    product = MyProductsModel.objects.get(id=id)
    my_product = MyProductsModel.objects.get_or_create(user_name=request.user,
                                                       name_application=product.name_application,
                                                       model=product.model)
    # my_product.quantity = 1
    # cart_product_form = CartAddProductForm()
    product.quantity -= 1
    # my_product.save()
    product.save()
    return HttpResponseRedirect(reverse('applications:user_read_product'))


class ApplicationDeleteView(DeleteView):
    model = ApplicationModel
    template_name = 'applications/applications-update-delete.html'
    success_url = reverse_lazy('applications:applications_read')


class ApplicationUpdateView(UpdateView, BaseClassContextMixin):
    model = ApplicationModel
    template_name = 'applications/applications-update-delete.html'
    form_class = ApplicationUpdateForm
    title = 'Обновление заявки'
    success_url = reverse_lazy('applications:applications_read')

applications/templates/applications/applications-create.html
{% extends 'applications/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Формирование заявки</h1>
                <form action="{% url 'applications:applications_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for=" {{ form.name.id_for_label }}">Тема заявки</label>
                               {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                            <label class="small mb-1" for="{{ form.cuty.id_for_label }}">Город</label>
                           {{ form.city }}
                        </div>
                    </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">

            </div>
        </footer>
    </div>
{% endblock %}

applications/templates/applications/applications-read.html
{% extends 'applications/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукта
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя дилера</th>
                                    <th>Тема заявки</th>
                                    <th>Грород дилера</th>
                                    <th>Описание</th>
                                    <th>Статус</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>

                                </tr>
                                <tbody>
                                {% for application in applications %}
                                    <tr>
                                        <td>{{ application.user_name }}</td>
                                        <td>{{ application.name }}</td>
                                        <td>{{ application.city }}</td>
                                        <td>{{ application.description }}</td>
                                        <td>
                                            {% if request.user.user_role != 'Сотрудник' and application.is_active == 'Одобрено' %}
                                                <a href="{% url 'applications:bye_product_read' %}">{{ application.is_active }}</a>
<!--                                                <a href="{% url 'applications:product_bye' application.id %}">{{ application.is_active }}</a>-->
                                            {% else%}
                                                {{ application.is_active }}
                                            {%endif%}
                                        </td>
                                        <td>
                                            {% if request.user.user_role == 'Сотрудник'%}

                                            <form action="{% url 'applications:applications_update_status1' application.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Отказать">
                                            </form>
                                            {%else%}
                                            <form action="{% url 'applications:applications_delete' application.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                                            </form>
                                            {%endif%}
                                        </td>
                                        <td>
                                            {% if request.user.user_role == 'Сотрудник'%}
                                            <form action="{% url 'applications:applications_update_status2' application.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-success btn-block" type="submit" value="Одобрить">
                                            </form>
                                            {%else%}
                                            <a href="{% url 'applications:applications_update' application.id %}">
                                                <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                            </a>
                                            {%endif%}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% if request.user.user_role != 'Сотрудник'%}
                    <div class="card-footer">
                        <a href="{% url 'applications:applications_create' %}">
                            <button class="btn btn-success">Сформировать заявку</button>
                        </a>
                    </div>
                    {%endif%}
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">

            </div>
        </footer>
    </div>

{% endblock %}

applications/templates/applications/applications-update-delete.html
{% extends 'applications/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Обновление заявки</h1>
                <div class="card-body">
                    <form action="{% url 'applications:applications_update' object.id %}" method="post" >
                    {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for=" {{ form.name.id_for_label }}">Тема заявки</label>
                                   {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                <label class="small mb-1" for="{{ form.city.id_for_label }}">Город</label>
                                        {{ form.city }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                    {{ form.description }}
                                </div>
                            </div>

                        </div>


                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'applications:applications_delete' object.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">

            </div>
        </footer>
    </div>

{% endblock %}

applications/templates/applications/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="u    tf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Admin</title>
    <link href="{% static  'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Портал Теле2</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'authapp:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    {% include 'applications/includes/siberia_bar.html' %}
    {% block content %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static  'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static  'js/datatable.js' %}"></script>
</body>
</html>

applications/templates/applications/bye_product_read.html
{% extends 'applications/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукта
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Категория</th>
                                    <th>Цвет девайса</th>
                                    <th>Название</th>
                                    <th>Размер памяти</th>
                                    <th>Количество на складе</th>
                                    <th>Цена</th>
                                    <th>В корзину</th>

                                </tr>
                                <tbody>
                               {% for product in products %}
                                    <tr>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.color }}</td>
                                        <td>{{ product.model }}</td>
                                        <td>{{ product.memory_size}}</td>
                                        <td>{{ product.quantity}}</td>
                                        <td>{{ product.price}}</td>
                                        <td><form action="{% url 'cart:cart_add' product.id %}" method="post">

                                            {% csrf_token %}
                                             <input class="btn btn-success btn-block" type="submit" value="Добавить">
                                            {{ cart_product_form }}
                                        </form></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">

            </div>
        </footer>
    </div>

{% endblock %}

applications/templates/applications/user_bye_products.html
{% extends 'applications/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукта
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя дилера</th>
                                    <th>Название категории</th>
                                    <th>Модель устройства</th>
                                    <th>Имеющееся колличетсво</th>
                                    <th>Купить</th>
                                </tr>
                                <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td>{{ product.user_name }}</td>
                                        <td>{{ product.name_application }}</td>
                                        <td>{{ product.model }}</td>
                                        <td>{{ product.quantity}}</td>

<!--                                        <td> <a href="{% url 'applications:user_bye_one_product' product.id %}">-->
<!--                                                <input class="btn btn-success btn-block" type="submit" value="Купить">-->
<!--                                             </a>-->
<!--                                        </td>-->
                                        <td><form action="{% url 'cart:cart_add' product.model.id %}" method="post">

                                            {% csrf_token %}
                                             <input class="btn btn-success btn-block" type="submit" value="Добавить">
                                            {{ cart_product_form }}
                                        </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">

            </div>
        </footer>
    </div>

{% endblock %}