applications/urls.py
from django.urls import path
from applications.views import ApplicationCreateView, ApplicationDeleteView, ApplicationUpdateView, \
    ApplicationStatus2DeleteView, ApplicationStatus1DeleteView, ProductByeCreateView, my_product_read, \
    applications_main, user_read_product, user_bye_product, user_bye_one_product, bye_product_read

app_name = 'applications'
urlpatterns = [


    # path('applications/', ApplicationListView.as_view(), name='applications_read'),
    path('applications/', applications_main, name='applications_read'),
    path('applications/create/', ApplicationCreateView.as_view(), name='applications_create'),
    path('applications-delete/<int:pk>/', ApplicationDeleteView.as_view(), name='applications_delete'),
    path('applications-update/<int:pk>/', ApplicationUpdateView.as_view(), name='applications_update'),
    path('applications-update-status1/<int:pk>/', ApplicationStatus1DeleteView.as_view(), name='applications_update_status1'),
    path('applications-update-status2/<int:pk>/', ApplicationStatus2DeleteView.as_view(), name='applications_update_status2'),
    path('product_bye/<int:pk>/', ProductByeCreateView.as_view(), name='product_bye'),
    path('product_read/', my_product_read, name='product_read'),
    path('user_read_product/', user_read_product, name='user_read_product'),
    path('user_bye_product/<str:user_name>/<str:city>/', user_bye_product, name='user_bye_product'),
    path('user_bye_one_product/<int:id>/', user_bye_one_product, name='user_bye_one_product'),
    # path('product_bye.html/<int:pk>/', product_bye, name='product_bye'),
    path('bye_product_read/', bye_product_read, name='bye_product_read'),

]

authapp/urls.py
from django.urls import path
# from authapp.views import
from authapp.views import login,register,logout,profile

app_name = 'authapp'
urlpatterns = [

    path('login/', login,name='login'),
    path('register/', register,name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('user_works/', include('user_works.urls', namespace='user_works')),
    # path('admins/', include('admins.urls', namespace='admins')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import products, ProductDetail

app_name = 'mainapp'
urlpatterns = [

    path('', products, name='products'),
    path('category/<int:id_category>', products, name='category'),
    path('page/<int:page>', products, name='page'),
    path('detail/<int:pk>/', ProductDetail.as_view(), name='detail'),
]

mainapp/models.py
from django.db import models


# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='product_image', blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f'{self.name}'


class Product_for_diller(models.Model):
    name = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.CharField(max_length=128, blank=True)
    model = models.CharField(max_length=128)
    memory_size = models.IntegerField(blank=True)
    price = models.IntegerField(blank=True)
    quantity = models.DecimalField(max_digits=8, decimal_places=2, blank=True)

    def __str__(self):
        return f'{self.model}'

mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render

import json
import os

from django.views.generic import DetailView

from mainapp.models import Product

MODULE_DIR = os.path.dirname(__file__)


# Create your views here.

def index(request):
    context = {
        'title': 'Geekshop', }
    return render(request, 'mainapp/index.html', context)


def products(request,id_category=None,page=1):

    context = {'title': 'Geekshop | Каталог', 'products': Product.objects.all()}
    return render(request, 'mainapp/products.html', context)


class ProductDetail(DetailView):
    """
    Контроллер вывода информации о продукте
    """
    model = Product
    template_name = 'mainapp/detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(ProductDetail, self).get_context_data(**kwargs)
    #     product = self.get_object()
    #     context['product'] = product
    #     return context

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static  'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}

    {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Портал Теле2 {% now "D d M Y" %} </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'mainapp:products' %}">Каталог <i class="fas fa-shopping-bag"></i>-->
<!--                    </a>-->
<!--                </li>-->
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">Войти <i
                                class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:profile' %}">{{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            admin <i class="fas fa-users-cog"></i>
                        </a>
                    </li>
                        {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}
<!-- Bootstrap core JavaScript -->
<script src="{% static  'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static  'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static  'js/basket.js' %}"></script>


<!-- FontAwesome script -->
<script src="{% static  'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">Подробная информация</h1>
                <div class="list-group">
                    <a href="{% url 'mainapp:products' %}" class="list-group-item">Все</a>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"> цена услуги - {{ product.price }} руб</li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer style="position:fixed; bottom:0; width:2000px" class="py-5 bg-dark">
        <div class="container" >
            <p class="m-0 text-center text-white">Copyright &copy; Портал Теле2</p>
        </div>
    </footer>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static  'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Портал Теле2</h1>
                        <p>
                            Добро пожаловать на портал Теле2, вы можете оформить заявку на участие в нашей компании
                        </p>
                    {% if user.is_authenticated %}
                    {%if request.user.user_role == 'Сотрудник' or request.user.user_role == 'Дилер'  %}
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'applications:applications_read' %}">
                            Мои заявки
                        </a>
                    </button>
                    {%endif%}
                    {%if request.user.user_role == 'Дилер'  %}
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'mainapp:products' %}">
                            Услуги
                        </a>
                    </button>
                    {%endif%}
                    {%if request.user.user_role == 'Пользователь'  %}
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'applications:user_read_product' %}">
                            Покупки
                        </a>
                    </button>
                    {%endif%}
                    {%endif%}
                </div>
            </div>
        </div>
    </section>
<footer style="position:fixed; bottom:0; width:2000px" class="py-5 bg-dark">
        <div class="container" >
            <p class="m-0 text-center text-white">Copyright &copy; Портал Теле2</p>
        </div>
</footer>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static  'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">

            <div class="col-lg-3">


            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-12">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>

                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {% include 'mainapp/includes/card.html' %}


            </div>

        </div>

    </div>

{% endblock %}

{% block footer %}
    <footer style="position:fixed; bottom:0; width:2000px" class="py-5 bg-dark">
        <div class="container" >
            <p class="m-0 text-center text-white">Copyright &copy; Портал Теле2</p>
        </div>
    </footer>
{% endblock %}